client_config_backend: settings
client_config:
  client_id:
  client_secret:

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

oauth_scope:
  - "https://www.googleapis.com/auth/drive"
